---
- name: Desktop configuration.
  hosts: localhost

  vars_files:
    - vars/main.yaml

  roles:
    - role: roles/ubuntu_base_desktop
      tags: ['base']
    - role: roles/docker_setup
      tags: ['docker']
