---
- name: Check-out dotfles
  ansible.builtin.git:
    repo: git@github.com:jalexm8/dotfiles.git
    dest: /home/{{ username }}/src/dotfiles
    version: "main"

- name: Install zsh
  ansible.builtin.package:
    name:
      - zsh
    state: present
  become: true

- name: Check oh-my-zsh is installed
  ansible.builtin.stat:
    path: /home/{{ username }}/.oh-my-zsh/
  register: oh_my_zsh_installed

- name: Download oh-my-zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /home/{{ username }}/src/oh-my-zsh-install.sh
    mode: '0700'
  when: not oh_my_zsh_installed.stat.exists

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: |
      sh /home/{{ username }}/src/oh-my-zsh-install.sh
  when: not oh_my_zsh_installed.stat.exists

- name: Create ohmyzsh themes dir
  ansible.builtin.file:
    path: /home/{{ username }}/.oh-my-zsh/custom/themes/
    state: directory
    mode: '0755'

- name: Check-out powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
    version: "master"

- name: Copy .p10k.zsh
  ansible.builtin.copy:
    src: /home/{{ username }}/src/dotfiles/.p10k.zsh
    dest: /home/{{ username }}/.p10k.zsh
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    backup: true

- name: Copy .zshrc
  ansible.builtin.copy:
    src: /home/{{ username }}/src/dotfiles/.zshrc
    dest: /home/{{ username }}/.zshrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    backup: true
