---
- name: Install VSCode dependencies
  ansible.builtin.package:
    name:
      - software-properties-common
      - apt-transport-https
      - wget
    state: present
  become: true

- name: Add Microsoft GPG key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true

- name: Add vscode repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  become: true

- name: Install vscode
  ansible.builtin.package:
    name:
      - code
    state: present
    update_cache: true
  become: true
